

import pyautogui
import time



 
pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)



 
pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
time.sleep(4)

pyautogui.press("win")
pyautogui.click(x=1296, y=82)
time.sleep(2)
pyautogui.write ("google chrome")
time.sleep(2)
pyautogui.click(x=1117, y= 202)
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(4)
pyautogui.write("https://www.youtube.com/shorts/mMME1gaDNDc")
time.sleep(2)
pyautogui.press("enter")
time.sleep(62)
pyautogui.click(x=465, y= 16)
